# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: ~/plugins/zenware/novembergallery/models/gallery/columns.yaml

# Model Class name
modelClass: ZenWare\NovemberGallery\Models\Gallery

# List Title
title: zenware.novembergallery::lang.entities.gallery_label

# Link URL for each record
recordUrl: zenware/novembergallery/galleries/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 15

# Display checkboxes next to each record
showCheckboxes: true

# Show icon for list setup
showSetup: true

# Show list as tree
showTree: false
treeExpanded: false

# Sorting
showSorting: 1

defaultSort:
    column: name
    direction: asc

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt